# Generated by Django 3.1.7 on 2022-01-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
