# Generated by Django 3.1.7 on 2022-01-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default='testaccess', max_length=2048),
            preserve_default=False,
        ),
    ]
