# Generated by Django 3.1.7 on 2022-03-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220327_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner_email',
            field=models.EmailField(default='nicolas.guelfi@achilio.com', max_length=254),
            preserve_default=False,
        ),
    ]
