# Generated by Django 3.1.7 on 2022-04-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_team_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stripe_customer_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
