version: "3.1"

services:
  web:
    image: mvm-auth
    build: .
    restart: always
    ports:
      - 8000:8000
    environment:
      - DJANGO_GOOGLE_OAUTH2_CLIENT_ID=293325499254-8h7bv5piflnjdoufjak8jjh03tpqss8b.apps.googleusercontent.com
      - DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET=OZeUkdunGSTQ7ZyvM7oDtabD
      - DJANGO_SECRET_KEY=secret
      - PORT=8000
      - SECRET_KEY=secret
      - GS_BUCKET_NAME="achilio-dev_auth-django-storage"
      - DATABASE_URL=sqlite:///db.sqlite
    volumes:
      - .:/app
    entrypoint: ./entrypoint-local.sh
